language: c
sudo: true
cache:
  directories:
    - "$HOME/.ghc"
    - "$HOME/.cabal"
    - "$HOME/.stack"
    - "$HOME/.local/bin"
    - "$TRAVIS_BUILD_DIR/.stack-work"

os:
  - linux
  - osx

env:
  global:
    # GITHUB_TOKEN
    secure: "sWmG2kixHTGta9sxPOmvErI7byDoSPjJKberqx2CVcPkBfepn6RPis5leVQiz8Bg0mnwqwMkPkXHGz2IkZ4g/lUKa+elvwqHqPeGybZJJ5OiaZK24MEGXn+ozixCTWrrG7lG/uSYc/OtX5z7spZ1HQkfsSsWSYjfRTUf+wuTDYQw59ztQFlX8s8CnYClnmo7JycVEMwtnHp+lol6XJwwmfj5ZO8ppQD50Sz8OLJwInb5+24re2u64GTKqVN8Zp/JLd854G3g3RiLInqQFd0k8MmeUrYIEhYk2enLhyWe31ZzfGYCgPkFgJ+/XmrJfsdRUgFp9uNhfezJl9kNZ1mUdjsUYWBEULVrFMNcSJL4OZdymOhkZ/HlAt2IjW+mxuVcHrdVijqwfMmc1/4VZ5uNOWCFJSWe7efiZUDAzjLqxHxSIBpxWElVt2cnnFf4wBTfT7dwT/FAwDWNiO3qClbhtv93Wn2OhGmhSuzZ38wc30orp/5C36qt5/f74lhLG+zk++I4zFRqHqOOy0ntwShm5YtDoc9iM4RU2Kx1SfKl65eOaFx3C8DK+mdoa/wIlgIKEvAtDBsa2wkmDOmORwE2KGY7PJfDV3uHOiECGDK/q/6JUnBOTghhRR3pI4YlZKZcCKvf2KxRsll3f/suFlT7SkLwVIGN9MFWaxEpBrZVOS8="

before_install:
  - set -e
  - "[ -d $HOME/.local/bin ] || mkdir -p $HOME/.local/bin"
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ \! -x $HOME/.local/bin/stack ]; then
      travis_retry curl -sSL https://get.haskellstack.org/ > $HOME/.local/bin/install-stack.sh
      sh $HOME/.local/bin/install-stack.sh -d $HOME/.local/bin
    fi
  - travis_wait stack --no-terminal setup

install:
  - set -e
  - stack --no-terminal install github-release
  - stack --no-terminal build --only-dependencies

script:
  - stack --no-terminal build

after_success:
  - |
    set -e
    owner="${TRAVIS_REPO_SLUG%%/*}"
    repo="${TRAVIS_REPO_SLUG#*/}"
    if [ -n "$TRAVIS_TAG" -a "$owner" == "mikemckibben" -a $repo == "ansible-ssh" ]; then
      gzip --best $(stack path --local-install-root)/bin/ansible-ssh
      github-release upload \
        --token "$GITHUB_TOKEN" \
        --owner "$owner" \
        --repo "$repo" \
        --tag "$TRAVIS_TAG" \
        --file "$(stack path --local-install-root)/bin/ansible-ssh.gz" \
        --name "ansible-ssh-$TRAVIS_TAG-$TRAVIS_OS_NAME-$(uname -m).gz"
    fi
