language: c
sudo: true
cache:
  directories:
    - "$HOME/.ghc"
    - "$HOME/.cabal"
    - "$HOME/.stack"
    - "$HOME/.local/bin"
    - "$TRAVIS_BUILD_DIR/.stack-work"
os:
  - linux
  - osx

env:
  global:
    # GITHUB_TOKEN
    secure: "bLTsp7Ho24iTKCDmgK8mtKqUwN5DaK/Sd790+lsfh8lBnOqL3HzSql5nI6/AnmKQVEU9qjCVNl1NQclUCfCgNHN9MCWuSPeE/mmXr7jPp8ryCcXQxTeyFeYAsCbTP7TmiKIpkl212273IHuBVSPaPIp8a9aWGeNaz/I+DKN9PASqjq27Fl1e4gg2k6fPoReXf30iwr2PNygCEA2Oat3j6r4DqG8qJ+cHPKLFCfKzMzpW4TEvvWCIOMxsSkpN9jqM85V/TDzpgZ92TT1TGRjTU60eYNTjKU/4SmwvUQ0ewY17csiBIV+Md1pZtIKO1vHiMXshXeWPy6t6Gh33mGZO+Skc13fcYyCqUFXygRTwsaePDwTeDq8Ovu2lAjoqWvE8t/IqX7hk0znetP+b477fITcKXGdTuYV+jFV2bPMMVQ8fDS0/7ypG3agQIee0hM5dC5HwBEjdMVrwRflNwFd2dcC+TmCvy2EqJ5lXfLiIxUZ25eEYSXKQIVzEh4HSvvSyIvAKwEtx3m8XuVSUGUqf3LDIk9Pp9BajCoJKIv121Wef7YNMTDU1AP9mUwvNxWvFBYhudKH3j22Mv3U8+d5qxdMcSbgVhXlm7ZB/99KLfaSEKVGd69F4aZ9Fpc578eUvFRCD3603hNyzLg2Kmqf83KJky8HbCDIdc7dG3FLa0zE="

before_install:
  - set -e
  - "[ -d $HOME/.local/bin ] || mkdir -p $HOME/.local/bin"
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ \! -x $HOME/.local/bin/stack ]; then
      travis_retry curl -sSL https://get.haskellstack.org/ > $HOME/.local/bin/install-stack.sh
      sh $HOME/.local/bin/install-stack.sh -d $HOME/.local/bin
    fi
  - travis_wait stack --no-terminal setup

install:
  - stack --no-terminal install github-release
  - stack --no-terminal build --only-dependencies

script:
  - stack --no-terminal build

after_success:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      gzip --best $(stack path --local-install-root)/bin/ansible-ssh
      github-release upload \
        --token "$GITHUB_TOKEN" \
        --owner "mikemckibben" \
        --repo "ansible-ssh" \
        --tag "$TRAVIS_TAG" \
        --file "$(stack path --local-install-root)/bin/ansible-ssh.gz" \
        --name "ansible-ssh-$TRAVIS_TAG-$TRAVIS_OS_NAME-$(uname -m).gz"
    fi
